/**
 * Slack short-name → Unicode for standard emoji only.
 *
 * Custom workspace emoji (and anything not in this map) are intentionally
 * dropped so customers only ever see normal emoji on the app side.
 *
 * Names match Slack's reaction payload (`reaction` field, no colons).
 * Skin-tone suffixes (`name::skin-tone-2`) are stripped before lookup.
 */

/** Strip Slack skin-tone / multi-part suffixes → base short name. */
export function normalizeSlackReactionName(name: string): string {
  const trimmed = name.trim().toLowerCase();
  if (!trimmed) return '';
  // "thumbsup::skin-tone-2" → "thumbsup"
  const base = trimmed.split('::')[0] ?? trimmed;
  return base;
}

/**
 * Map a Slack reaction name to a single Unicode emoji, or null if custom /
 * unknown (do not surface to customers).
 */
export function slackReactionToUnicode(name: string): string | null {
  const key = normalizeSlackReactionName(name);
  if (!key) return null;
  return SLACK_STANDARD_EMOJI[key] ?? null;
}

/** True when this Slack reaction name maps to a standard Unicode emoji. */
export function isStandardSlackReaction(name: string): boolean {
  return slackReactionToUnicode(name) != null;
}

/**
 * Curated Slack short names used in support threads.
 * Prefer aliases Slack actually sends (`+1`, `heart`, `white_check_mark`, …).
 */
const SLACK_STANDARD_EMOJI: Record<string, string> = {
  // Hands / gestures
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  clap: '👏',
  wave: '👋',
  raised_hands: '🙌',
  pray: '🙏',
  muscle: '💪',
  ok_hand: '👌',
  point_up: '☝️',
  point_up_2: '👆',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  v: '✌️',
  metal: '🤘',
  writing_hand: '✍️',
  handshake: '🤝',
  crossed_fingers: '🤞',
  call_me_hand: '🤙',
  // Hearts / love
  heart: '❤️',
  heavy_heart_exclamation: '❣️',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  orange_heart: '🧡',
  two_hearts: '💕',
  sparkling_heart: '💖',
  heartpulse: '💗',
  heartbeat: '💓',
  revolving_hearts: '💞',
  cupid: '💘',
  gift_heart: '💝',
  broken_heart: '💔',
  // Faces
  smile: '😄',
  laughing: '😆',
  blush: '😊',
  smiley: '😃',
  relaxed: '☺️',
  smirk: '😏',
  heart_eyes: '😍',
  kissing_heart: '😘',
  kissing: '😗',
  kissing_smiling_eyes: '😙',
  kissing_closed_eyes: '😚',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  stuck_out_tongue_closed_eyes: '😝',
  wink: '😉',
  grin: '😁',
  joy: '😂',
  rofl: '🤣',
  sweat_smile: '😅',
  satisfied: '😆',
  innocent: '😇',
  smiling_face_with_3_hearts: '🥰',
  star_struck: '🤩',
  thinking_face: '🤔',
  thinking: '🤔',
  raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  roll_eyes: '🙄',
  hushed: '😯',
  frowning: '😦',
  anguished: '😧',
  open_mouth: '😮',
  astonished: '😲',
  flushed: '😳',
  pleading_face: '🥺',
  frowning_face: '☹️',
  slightly_frowning_face: '🙁',
  confused: '😕',
  worried: '😟',
  disappointed: '😞',
  confounded: '😖',
  cry: '😢',
  sob: '😭',
  persevere: '😣',
  disappointed_relieved: '😥',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  yawning_face: '🥱',
  triumph: '😤',
  rage: '😡',
  angry: '😠',
  smiling_imp: '😈',
  imp: '👿',
  skull: '💀',
  skull_and_crossbones: '☠️',
  hankey: '💩',
  poop: '💩',
  clown_face: '🤡',
  ghost: '👻',
  alien: '👽',
  space_invader: '👾',
  robot_face: '🤖',
  robot: '🤖',
  smiley_cat: '😺',
  smile_cat: '😸',
  joy_cat: '😹',
  heart_eyes_cat: '😻',
  smirk_cat: '😼',
  kissing_cat: '😽',
  scream_cat: '🙀',
  crying_cat_face: '😿',
  pouting_cat: '😾',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  zipper_mouth_face: '🤐',
  money_mouth_face: '🤑',
  face_with_thermometer: '🤒',
  nerd_face: '🤓',
  face_with_monocle: '🧐',
  sunglasses: '😎',
  star_struck_face: '🤩',
  partying_face: '🥳',
  woozy_face: '🥴',
  exploding_head: '🤯',
  cold_face: '🥶',
  hot_face: '🥵',
  face_with_hand_over_mouth: '🤭',
  shushing_face: '🤫',
  face_with_symbols_on_mouth: '🤬',
  // Status / checks
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  ballot_box_with_check: '☑️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  heavy_multiplication_x: '✖️',
  o: '⭕',
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  info: 'ℹ️',
  information_source: 'ℹ️',
  question: '❓',
  grey_question: '❔',
  exclamation: '❗',
  grey_exclamation: '❕',
  bangbang: '‼️',
  interrobang: '⁉️',
  // Work / objects
  eyes: '👀',
  eye: '👁️',
  fire: '🔥',
  100: '💯',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  zap: '⚡',
  boom: '💥',
  collision: '💥',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  trophy: '🏆',
  medal: '🏅',
  rocket: '🚀',
  airplane: '✈️',
  bulb: '💡',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  mag: '🔍',
  mag_right: '🔎',
  memo: '📝',
  pencil: '✏️',
  pencil2: '✏️',
  book: '📖',
  books: '📚',
  bookmark: '🔖',
  link: '🔗',
  paperclip: '📎',
  pushpin: '📌',
  round_pushpin: '📍',
  clipboard: '📋',
  file_folder: '📁',
  open_file_folder: '📂',
  calendar: '📅',
  date: '📅',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  moneybag: '💰',
  money_with_wings: '💸',
  credit_card: '💳',
  dollar: '💵',
  email: '📧',
  envelope: '✉️',
  incoming_envelope: '📨',
  'e-mail': '📧',
  mailbox: '📫',
  phone: '☎️',
  telephone: '☎️',
  iphone: '📱',
  calling: '📲',
  computer: '💻',
  keyboard: '⌨️',
  desktop_computer: '🖥️',
  printer: '🖨️',
  camera: '📷',
  camera_with_flash: '📸',
  video_camera: '📹',
  movie_camera: '🎥',
  tv: '📺',
  radio: '📻',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  alarm_clock: '⏰',
  watch: '⌚',
  stopwatch: '⏱️',
  timer_clock: '⏲️',
  // Nature / misc
  sunny: '☀️',
  cloud: '☁️',
  umbrella: '☂️',
  snowflake: '❄️',
  snowman: '⛄',
  zap_cloud: '⚡',
  rainbow: '🌈',
  ocean: '🌊',
  earth_americas: '🌎',
  earth_africa: '🌍',
  earth_asia: '🌏',
  // Food (common reactions)
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  wine_glass: '🍷',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  cookie: '🍪',
  doughnut: '🍩',
  cake: '🍰',
  birthday: '🎂',
  // Numbers / symbols
  zero: '0️⃣',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  keycap_ten: '🔟',
  hash: '#️⃣',
  asterisk: '*️⃣',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_left: '⬅️',
  arrow_right: '➡️',
  arrows_clockwise: '🔃',
  arrows_counterclockwise: '🔄',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  heavy_division_sign: '➗',
  infinity: '♾️',
  recycle: '♻️',
  copyright: '©️',
  registered: '®️',
  tm: '™️',
  // People (simple)
  wave_hello: '👋',
  bow: '🙇',
  raised_hand: '✋',
  raised_back_of_hand: '🤚',
  hand: '✋',
  palm_down_hand: '🫳',
  palm_up_hand: '🫴',
  leftwards_hand: '🫲',
  rightwards_hand: '🫱',
  // Misc support-ish
  speech_balloon: '💬',
  thought_balloon: '💭',
  loudspeaker: '📢',
  mega: '📣',
  bell: '🔔',
  no_bell: '🔕',
  mute: '🔇',
  speaker: '🔈',
  sound: '🔉',
  loud_sound: '🔊',
  musical_note: '🎵',
  notes: '🎶',
  thumbsup_all: '👍',
  ok: '🆗',
  new: '🆕',
  free: '🆓',
  cool: '🆒',
  up: '🆙',
  vs: '🆚',
  sos: '🆘',
  id: '🆔',
  abc: '🔤',
  abcd: '🔡',
  capital_abcd: '🔠',
  '1234': '🔢',
  symbols: '🔣',
  parking: '🅿️',
  wheelchair: '♿',
  mens: '🚹',
  womens: '🚺',
  restroom: '🚻',
  baby_symbol: '🚼',
  wc: '🚾',
  passport_control: '🛂',
  customs: '🛃',
  baggage_claim: '🛄',
  left_luggage: '🛅',
  // Flags (minimal — national flags often custom; keep a few symbols)
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  rainbow_flag: '🏳️‍🌈',
  pirate_flag: '🏴‍☠️',
  white_flag: '🏳️',
  black_flag: '🏴',
};
